### ISSUE TITLE
Does not update on prayer change when turned on for a long time

### ISSUE THREAD

**Issue by A-q-p-W** [j-cob44/max-hit-calc#25]
Plugin does not update max hit when changing prayer or hitpoints (in the case of dharok's) if you leave it on for a long time i.e. between multiple sessions and launches of the client and your PC. Turning it off and back on again resolves this strangely enough

**Comment by A-q-p-W** [comment]
Hi, yes version is 1.10.3 as you can see in the screenshot below. Great plugin aside from this issue, glad to see one that is maintained unlike the other one which seems to have been abandoned.
![image](https://github.com/j-cob44/max-hit-calc/assets/33811889/f2386af0-121a-4e37-a35e-74e94cee30b8)

**Comment by j-cob44** [comment]
Ok, I'll keep an eye out for this bug.

Does restarting Runelite fix this issue or do you always have to turn on and off the plugin to fix it?

**Comment by j-cob44** [comment]
Hey @A-q-p-W,

I've been trying to test for this whenever I can, so far I've tested up to 12 hours of Runelite being open with no issues. There is also a chance that this is fixed in version 1.11 as all leagues 4 code was removed which may have made it unstable without leagues 4 being in game anymore.

Can you estimate how long in hours it took for it to break? Also, were you putting your computer to sleep with Runelite open or anything similar to that?

**Comment by A-q-p-W** [comment]
Hi, yeah I put my computer to sleep with RuneLite open quite often. It's possible that it's fixed now or only happens in conjunction with Dharok's because I've had Max Hit on for a few days now without the bug re-occuring whereas before it would have happened by now. Also re: your previous message, restarting RuneLite didn't fix it when it occurred, only turning the plugin off and on again did.

**Comment by A-q-p-W** [comment]
Okay just after I posted that comment the bug has returned... I don't know if having had Dharok's on had anything to do with it or not, or changing my melee weapon's attack style to accurate caused a conflict with my Attack Styles plugin because those are the only things I changed. Here is a clip of the bug just for clarity.

https://github.com/j-cob44/max-hit-calc/assets/33811889/ed0c84da-60e5-4c93-bcb7-c9f79248c1ad

**Comment by j-cob44** [comment]
Very very interesting. Thanks for the video, it will help a lot.

How long would you say you had Runelite open in this case? 
And is it only changing prayers and attack styles that does not update the infobox when this happens? This might narrow it down considerably.

**Comment by j-cob44** [comment]
Ok, I believe I solved the issue. I'm pushing a fix right now and it will be released in version 1.12.1.

The issue is that the plugin was waiting for the welcome screen to start loading data. I made it like this because before you click "CLICK HERE TO PLAY" it would try to load values that we're available and would sometimes crash.

![image](https://github.com/j-cob44/max-hit-calc/assets/23692043/b2f825cc-c3b2-4a81-9e60-8c53affb36f8)

However, if you login at a dangerous place, (ex: in the wilderness) this welcome screen will never appear and you would load straight into the game. This needed to be fixed and now has been. Within hopefully a few days, the version will be updated in Runelite. If this does not fix your issue, please let me know.

Also, thank you for reporting the Dharok's bug, that has been fixed as well and is also in the next version.

**Comment by A-q-p-W** [comment]
> Ok, I believe I solved the issue. I'm pushing a fix right now and it will be released in version 1.12.1.
> 
> The issue is that the plugin was waiting for the welcome screen to start loading data. I made it like this because before you click "CLICK HERE TO PLAY" it would try to load values that we're available and would sometimes crash.
> 
> ![image](https://private-user-images.githubusercontent.com/23692043/305737994-b2f825cc-c3b2-4a81-9e60-8c53affb36f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDIwNDEsIm5iZiI6MTcwODMwMTc0MSwicGF0aCI6Ii8yMzY5MjA0My8zMDU3Mzc5OTQtYjJmODI1Y2MtYzNiMi00YTgxLTllNjAtOGM1M2FmZmIzNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAwMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YTJjNTE0Nzk2NWM4ZGY1ZTI0MWQ3ZDgyOWFiN2Y4YzA2N2EwNzQ5Y2RiZTMzMzJlMDBjMGM0ZTA5ZTlmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a1oqZ8oq4L7tJ57OszQ5A1Tfg4tR38HxP7sjQYcdP10)
> 
> However, if you login at a dangerous place, (ex: in the wilderness) this welcome screen will never appear and you would load straight into the game. This needed to be fixed and now has been. Within hopefully a few days, the version will be updated in Runelite. If this does not fix your issue, please let me know.
> 
> Also, thank you for reporting the Dharok's bug, that has been fixed as well and is also in the next version.

Ohhhh haha, yes I log in inside the Wilderness quite often, sometimes after closing the client etc. so the welcome screen would be there in any other area. Hopefully that fixes things! And thanks for fixing the Dharok's bug, that will be quite useful to me.

**Comment by j-cob44** [comment]
Hey @A-q-p-W, any news on if this is still a problem for you?

**Comment by A-q-p-W** [comment]
Hi, seems to be fixed now! :D Haven't seen it happen in ages, thanks so much
